# Quaternions?

***

In [1]:
import numpy as np

In [2]:
I = np.array([[1, 0], [0, 1]])

I

array([[1, 0],
       [0, 1]])

In [3]:
x = np.array([[1, 0], [0, -1]])

x

array([[ 1,  0],
       [ 0, -1]])

In [4]:
y = np.array([[0, 1], [1, 0]])

y

array([[0, 1],
       [1, 0]])

In [5]:
xy = x @ y

xy

array([[ 0,  1],
       [-1,  0]])

In [6]:
yx = y @ x

yx

array([[ 0, -1],
       [ 1,  0]])

In [7]:
x @ x

array([[1, 0],
       [0, 1]])

In [8]:
y @ y

array([[1, 0],
       [0, 1]])

In [9]:
(y @ y == x @ x).all()

True

In [10]:
xy @ xy

array([[-1,  0],
       [ 0, -1]])

In [11]:
yx @ yx

array([[-1,  0],
       [ 0, -1]])

In [12]:
xy @ yx

array([[1, 0],
       [0, 1]])

In [13]:
(-x @ y == y @ x).all()

True

In [14]:
-x @ -y

array([[ 0,  1],
       [-1,  0]])

In [15]:
G = np.array([I, x, y, xy, -I, -x, -y, -xy])

G

array([[[ 1,  0],
        [ 0,  1]],

       [[ 1,  0],
        [ 0, -1]],

       [[ 0,  1],
        [ 1,  0]],

       [[ 0,  1],
        [-1,  0]],

       [[-1,  0],
        [ 0, -1]],

       [[-1,  0],
        [ 0,  1]],

       [[ 0, -1],
        [-1,  0]],

       [[ 0, -1],
        [ 1,  0]]])

In [16]:
np.array(list(map(lambda g: g @ g, G)))

array([[[ 1,  0],
        [ 0,  1]],

       [[ 1,  0],
        [ 0,  1]],

       [[ 1,  0],
        [ 0,  1]],

       [[-1,  0],
        [ 0, -1]],

       [[ 1,  0],
        [ 0,  1]],

       [[ 1,  0],
        [ 0,  1]],

       [[ 1,  0],
        [ 0,  1]],

       [[-1,  0],
        [ 0, -1]]])

In [17]:
xy @ xy

array([[-1,  0],
       [ 0, -1]])

In [18]:
xy @ xy @ xy 

array([[ 0, -1],
       [ 1,  0]])

In [19]:
xy @ xy @ xy @ xy

array([[1, 0],
       [0, 1]])

In [20]:
x @ y

array([[ 0,  1],
       [-1,  0]])

In [21]:
y @ x

array([[ 0, -1],
       [ 1,  0]])

In [22]:
x @ xy

array([[0, 1],
       [1, 0]])

In [23]:
(xy @ xy @ xy) @ x

array([[0, 1],
       [1, 0]])

In [24]:
I

array([[1, 0],
       [0, 1]])

In [25]:
-I

array([[-1,  0],
       [ 0, -1]])

In [26]:
x

array([[ 1,  0],
       [ 0, -1]])

In [27]:
-x

array([[-1,  0],
       [ 0,  1]])

In [28]:
y

array([[0, 1],
       [1, 0]])

In [29]:
-y

array([[ 0, -1],
       [-1,  0]])

In [30]:
xy

array([[ 0,  1],
       [-1,  0]])

In [31]:
-xy

array([[ 0, -1],
       [ 1,  0]])

In [32]:
G = np.array([I, x, y, xy, -I, -x, -y, -xy])

In [33]:
G_labels = ['  I', '  x', '  y', ' xy', ' -I', ' -x', ' -y', '-xy'];

In [34]:
for g1 in G:
  for g2 in G:
    gi = list(filter(lambda i: (G[i] == g1 @ g2).all(), range(len(G))))[0]
    print(G_labels[gi], end=', ')
  print()

  I,   x,   y,  xy,  -I,  -x,  -y, -xy, 
  x,   I,  xy,   y,  -x,  -I, -xy,  -y, 
  y, -xy,   I,  -x,  -y,  xy,  -I,   x, 
 xy,  -y,   x,  -I, -xy,   y,  -x,   I, 
 -I,  -x,  -y, -xy,   I,   x,   y,  xy, 
 -x,  -I, -xy,  -y,   x,   I,  xy,   y, 
 -y,  xy,  -I,   x,   y, -xy,   I,  -x, 
-xy,   y,  -x,   I,  xy,  -y,   x,  -I, 


***

### End