# Random Numbers in numpy

***

In [1]:
# Numerical arrays, random numbers.
import numpy as np

# Plots.
import matplotlib.pyplot as plt

## Python Standard Library

https://docs.python.org/3/library/random.html

***

In [2]:
# The random module from the standard library.
import random

In [3]:
# Using autocomplete, we can a get a flavour of the module.
# Putting a question mark in front of a function name prints
# a little help message.
?random.randint

Signature: random.randint(a, b)
Docstring:
Return random integer in range [a, b], including both end points.
        
File:      ~/.miniconda/lib/python3.10/random.py
Type:      method

In [4]:
# Based on the above, we can generate a random integer between
# 10 and 20, inclusive.
random.randint(10, 20)

17

In [5]:
# Generate a list of 100 random integers between 1 and 10.
L = [random.randint(1, 10) for i in range(100)]

# Show the first ten items of L.
L[:10]

[10, 9, 7, 9, 7, 8, 3, 5, 5, 2]

In [6]:
# List of car makes.
makes = ['Toyota', 'Skoda', 'Ford', 'Renault']

In [7]:
# Select one at random.
random.choice(makes)

'Renault'

In [8]:
# Select ten random makes (with replacement).
random.choices(makes, k=10)

['Renault',
 'Toyota',
 'Ford',
 'Ford',
 'Renault',
 'Skoda',
 'Ford',
 'Ford',
 'Renault',
 'Renault']

In [9]:
# First eight letters.
letters = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']

In [10]:
# Shuffle them.
random.shuffle(letters)

In [11]:
# Look at letters after shuffle.
letters

['C', 'A', 'B', 'H', 'E', 'G', 'F', 'D']

In [12]:
# Random selection without replacement.
random.sample(letters, k=5)

['F', 'B', 'A', 'D', 'E']

In [13]:
# Random real (floating-point) number. [0.0, 1.0)
random.random()

0.04348037300480778

In [14]:
# Pick a random floating point number between 0.0 and 100.0. [0.0, 100.0]
random.uniform(0.0, 100.0)

20.21966309683506

## numpy

[numpy API Reference: Random sampling](https://numpy.org/doc/stable/reference/random/index.html)

https://numpy.org/doc/stable/reference/random/index.html

***

In [15]:
# Random Number Generator (RNG) for generating random numbers.
rng = np.random.default_rng()

In [16]:
# Generate random floating point numbers in the interval 0.0 (included) to 1.0 (excluded).
rng.random(10)

array([0.03868619, 0.11603755, 0.52655561, 0.88802599, 0.28810038,
       0.49254221, 0.2599568 , 0.67472017, 0.6185569 , 0.535634  ])

Generate numbers on a standard Normal distribution.

The mean is 0.0 and standard deviation is 1.0.

The numbers generated should be, on average, centred on 0.0.

More than 99% of the numbers generated should be in the interval (-3.0, 3.0).

In [17]:
# Generate numbers on a standard Normal distribution.
rng.standard_normal(100)

array([ 6.10823106e-01, -8.80754573e-01, -5.07323673e-01, -7.31630817e-01,
       -1.69208163e+00,  7.24182943e-01,  1.65183558e+00,  9.05821688e-01,
        1.96374699e-03, -2.48340588e+00, -1.48320222e+00,  2.30078639e+00,
       -6.62779545e-01, -6.25894403e-01,  2.07630099e+00,  4.58670586e-01,
        3.28214191e-01, -8.13389843e-01, -1.15316757e+00, -3.13692204e-01,
        2.84497483e-01,  1.08071909e-01, -9.31309515e-02,  5.53686126e-01,
        2.00018384e-01,  1.67456463e+00, -7.33604768e-01,  8.82114241e-01,
       -2.24405468e-01, -3.94123514e-01,  1.49227890e+00, -7.80179086e-02,
        8.08199101e-01,  4.73149351e-01,  8.84228871e-01,  6.91480708e-01,
        2.55859891e+00,  1.17049681e+00,  3.98225078e-01, -5.01267886e-01,
       -6.99190028e-01,  6.96009483e-01, -5.63405881e-01,  2.09771461e+00,
        1.97252939e+00,  3.69329498e-01, -1.15331529e+00, -6.19721714e-01,
        2.76322730e-01, -4.85536604e-01,  1.18816090e+00,  1.43295566e+00,
       -2.21003604e+00,  

In [18]:
# Generated 15 integers between 10 (included) and 20 (excluded).
rng.integers(low=10, high=20, size=15) 

array([13, 10, 11, 10, 11, 10, 16, 11, 13, 15, 11, 16, 17, 10, 16])

***

#### End